import type { Metadata } from "next";
import { Heebo } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import FooterSection from "./components/FooterSection";

const heebo = Heebo({
  subsets: ['latin'],
  });

export const metadata: Metadata = {
  title: "UI Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={heebo.className}>
      <div>
      <Navbar/>
      </div>
      
        {children}
        <FooterSection/>
        </body>
      
    </html>
  );
}
